kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: spawn-load-users-to-keycloak-shared
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: nfs-storage
    volume.kubernetes.io/storage-provisioner: nfs-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: managed-storage
  volumeMode: Filesystem
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: lookup-policy-imagestream
spec:
  params:
    - description: Image stream
      name: image_stream
      type: string
    - description: Local policy
      name: local_policy
      type: string
  steps:
    - args:
        - >-
          echo Updating ImageStream $(inputs.params.image_stream)
          

          oc patch is/$(inputs.params.image_stream) -p '{"spec":
          {"lookupPolicy":{"local":$(inputs.params.local_policy)}}}'
          

          echo -----------------------------------
      command:
        - /bin/bash
        - '-c'
      image: 'image-registry.openshift-image-registry.svc:5000/openshift/cli:latest'
      name: patch
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: apply-manifests
spec:
  params:
    - default: k8s
      description: The directory in source that contains yaml manifests
      name: manifest_dir
      type: string
  steps:
    - args:
        - >-
          echo Applying manifests in $(inputs.params.manifest_dir) directory
          

          oc apply -f $(inputs.params.manifest_dir)
          

          echo -----------------------------------
      command:
        - /bin/bash
        - '-c'
      image: 'image-registry.openshift-image-registry.svc:5000/openshift/cli:latest'
      name: apply
      workingDir: /workspace/source
  workspaces:
    - name: source
---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: spawn-load-users-to-keycloak
spec:
  params:
    - default: spawn-load-users-to-keycloak
      description: name of the deployment to be patched
      name: deployment-name
      type: string
    - default: 'https://github.com/h3nrique/spawn-load-users-to-keycloak'
      description: url of the git repo for the code of deployment
      name: git-url
      type: string
    - default: master
      description: revision to be used from repo of the code for deployment
      name: git-revision
      type: string
    - default: >-
        image-registry.openshift-image-registry.svc:5000/example/spawn-load-users-to-keycloak
      description: image to be build from the code
      name: IMAGE
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.git-url)
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: revision
          value: $(params.git-revision)
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: jib-maven
      params:
        - name: IMAGE
          value: $(params.IMAGE)
        - name: MAVEN_IMAGE
          value: docker.io/library/maven:3-openjdk-21
      runAfter:
        - fetch-repository
      taskRef:
        kind: ClusterTask
        name: jib-maven
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: update-imagestream
      params:
        - name: image_stream
          value: $(params.deployment-name)
        - name: local_policy
          value: 'true'
      runAfter:
        - jib-maven
      taskRef:
        kind: Task
        name: lookup-policy-imagestream
    - name: apply-manifests
      runAfter:
        - update-imagestream
      taskRef:
        kind: Task
        name: apply-manifests
      workspaces:
        - name: source
          workspace: shared-workspace
  workspaces:
    - name: shared-workspace
---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: spawn-load-users-to-keycloak-1
  labels:
    tekton.dev/pipeline: spawn-load-users-to-keycloak
spec:
  params:
    - name: deployment-name
      value: spawn-load-users-to-keycloak
    - name: git-url
      value: 'https://github.com/h3nrique/spawn-load-users-to-keycloak'
    - name: git-revision
      value: master
    - name: IMAGE
      value: >-
        image-registry.openshift-image-registry.svc:5000/example/spawn-load-users-to-keycloak
  pipelineRef:
    name: spawn-load-users-to-keycloak
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: spawn-load-users-to-keycloak-shared
